### ISSUE TITLE
Send reminders to groups

### ISSUE THREAD

**Issue by alirezaomidi** [maratonime/contestwatcher#27]
Currently, the bot does not send reminders to groups, only to users. I think it should do it also.

**Comment by yancouto** [comment]
Hi @alirezaomidi, the bot already sends reminders to groups. The problem you're facing is probably because you added the bot to a group and then upgraded it to a supergroup. In this case the bot fails to work (issue #14).

Please remove the bot from the group and add it again, this should make it work. Please let us know :)

**Comment by alirezaomidi** [comment]
Sorry! No problem at all! I just hadn't `/start` the bot -_-
