### ISSUE TITLE
Rating change is not working

### ISSUE THREAD

**Issue by sharifMinhazul** [maratonime/contestwatcher#37]
Rating change for handle "[Bar-B-Q](http://codeforces.com/profile/Bar-B-Q)" is not showing. But the handle is in the list :(

**Comment by gabrielrussoc** [comment]
This is most likely due to case issues.

https://github.com/maratonime/contestwatcher/blob/6cd87c31f71f4d80d9f84877c8f08306971694f9/fetchers/codeforces.js#L24

In this function we compare the lowercased handles from the codeforces API with the database handles. For some reason, your handle is not lowercased on the database (which should be because of #33 ).

**Comment by yancouto** [comment]
I hate to say this, but removing the handle and adding it again may fix this. :P

**Comment by gabrielrussoc** [comment]
it won't

we assume that the handles are lowercased on the database, but they are not.

my guess is most handles are working because we manually lowercased everything in #33

**Comment by gabrielrussoc** [comment]
see #33
